language: crystal
script: make spec

os:
  - linux
  # TODO: Re-add OS X when Travis improves run times.
  # Alternatively: introduce OS X builds only on master, not on PRs
  # - osx
crystal:
  - latest
  - nightly
  
matrix:
  allow_failures:
  - crystal: nightly
  
